name: textfield_flutter
description: "Flutter library that provides customizable text input fields with error handling and validation features"
version: 0.0.2
homepage: https://github.com/rahul-gola/textfield_flutter.git

environment:
  sdk: '>=2.19.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0
