name: textfield_flutter
description: "A new Flutter project."
version: 0.0.1
homepage: https://github.com/rahul-gola/textfield_flutter.git

environment:
  sdk: '>=2.19.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0
